### ISSUE TITLE
an issue about visualizing floorplane

### ISSUE THREAD

**Issue by godhj93** [bertjiazheng/Structured3D#39]
Hi, I am testing the Structured3D dataset for my research. 

so far, I have downloaded the dataset and am trying to visualize it.

wireframe and plane work well with the command as follows:
```
python visualize_3d.py --path /media/hj/One\ Touch/Structured3D_Dataset/Structured3D --scene 00000 --type wireframe

python visualize_3d.py --path /media/hj/One\ Touch/Structured3D_Dataset/Structured3D --scene 00000 --type plane
```
but when i run the code with floorplane argment following issue happens
```
(test) hj@lab:~/Projects/3dmap/Structured3D$ python visualize_3d.py --path /media/hj/One\ Touch/Structured3D_Dataset/Structured3D --scene 00000 --type floorplan
Traceback (most recent call last):
  File "/home/hj/Projects/3dmap/Structured3D/visualize_3d.py", line 368, in <module>
    main()
  File "/home/hj/Projects/3dmap/Structured3D/visualize_3d.py", line 364, in main
    visualize_floorplan(annos)
  File "/home/hj/Projects/3dmap/Structured3D/visualize_3d.py", line 336, in visualize_floorplan
    plot_floorplan(annos, polygons)
  File "/home/hj/Projects/3dmap/Structured3D/visualize_3d.py", line 283, in plot_floorplan
    patch = PolygonPatch(polygon, facecolor=semantics_cmap[poly_type], alpha=0.5)
  File "/home/hj/anaconda3/envs/test/lib/python3.9/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "/home/hj/anaconda3/envs/test/lib/python3.9/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "/home/hj/anaconda3/envs/test/lib/python3.9/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

```

Is there any solution?

Thanks

**Comment by bertjiazheng** [comment]
It seems you use a higher version of shapely, please try to downgrade it.

**Comment by godhj93** [comment]
Cool, shapely 1.8.5 works
