### ISSUE TITLE
Issue with mesh visulization

### ISSUE THREAD

**Issue by TheScientist1900** [bertjiazheng/Structured3D#50]
Hi, when I run visualize_mesh.py, it shows:
Traceback (most recent call last):
  File "visualize_mesh.py", line 266, in <module>
    main()
  File "visualize_mesh.py", line 262, in main
    visualize_mesh(args)
  File "visualize_mesh.py", line 239, in visualize_mesh
    mesh = create_plane_mesh(corners, corner_floor, textures, texture_floor, texture_ceiling,
  File "visualize_mesh.py", line 125, in create_plane_mesh
    mesh.texture = open3d.geometry.Image(textures)
AttributeError: 'open3d.cpu.pybind.geometry.TriangleMesh' object has no attribute 'texture'

And I delete the code:
mesh.texture = open3d.geometry.Image(textures)

it works, but the visualization of layout  is not the same as in your readme.

**Comment by ShametHuang** [comment]
currently having this problem too,it seems that vertex and UV indices are misaligned ,I wonder if you have solved the problem，thanks
